services:
  stats-server:
    build: stats-server/server
    container_name: stats-server
    ports:
      - "9090:9090"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://host.docker.internal:5433/stats-db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=admin
      - SERVER_PORT=9090

  stats-db:
    image: postgres:17-alpine
    container_name: stats-db
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=postgres
      - POSTGRES_DB=stats-db
    volumes:
      - store-stats:/db_store

  ewm-service:
    build: ewm-service
    container_name: ewm-service
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://host.docker.internal:5434/ewm-db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=admin
      - SERVER_PORT=8080

  ewm-db:
    image: postgres:17-alpine
    container_name: ewm-db
    ports:
      - "5434:5432"
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=postgres
      - POSTGRES_DB=ewm-db
    volumes:
      - store-main:/db_store

volumes:
  store-stats:
  store-main:

